FROM php:7.4-apache

WORKDIR /var/www/html
COPY index.html /var/ww/html
COPY conexao.php /var/www/html

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-configure gd --with-freestyle --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install pdo-mysql \
    && docker-php-ext-installmysqli

EXPOSE 80
